openapi: 3.0.0
info:
  title: Matrix API
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /matrix:
    post:
      summary: Accept a matrix with JWT
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
                items:
                  type: number
      responses:
        '200':
          description: Matrix received successfully

security:
  - bearerAuth: []
